config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "plants#index"
  resources :plants, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
    belongs_to :user
    geocoded_by :zipcode
    after_validation :geocode
    validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    
   def index
        @plants = Plant.all
    end
    
    def new
        @plant = Plant.new
    end
 
    

    def create
        plant = current_user.plants.create(plant_params)
  if @plant.valid?
    redirect_to root_path
  else
    render :new, status: :unprocessable_entity
  end
    end

    def show
        @plant = Plant.find(params[:id])
    end

    private

    def plant_params
      params.require(:plant).permit(:name, :zipcode)
    end

    def update
  @plant = Plant.find(params[:id])

  if @plant.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end

  @plant.update_attributes(plant_params)
  if @plant.valid?
    redirect_to root_path
  else
    render :edit, status: :unprocessable_entity
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dulceverdegardens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Dulce Verde Gardens', root_path, class: 'navbar-brand' %>  
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">

        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <a class="nav-link" href="#">About the Gardener</a>
          </li>
           <li class="nav-item">
        <%= link_to new_plant_path, class: 'nav-link' do %>
        <i class="fas fa-seedling"></i>
        Your Garden
        <% end %>
      </li>
        </ul>
        <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
    </li>
      <% end %>
    </ul>
      </div>
    </nav>

    <%= yield %>


  </body>
</html>

app/views/plants/index.html.erb
<% @plants.each do |plant| %>
 <div class="booyah-box col-10 offset-1">
    <i><%= plant.zipcode %></i><br /><br />
     <% if plant.user.present? %>
      <small><%= plant.user.email %></small>
    <% end %>
    </div>
<% end %>

app/views/plants/new.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Share Your Garden</h1>
<%= simple_form_for @plant do |f| %>
 <%= f.input :name %>
 <%= f.input :zipcode %>
 <br />
 <%= f.submit 'Share', class: 'btn btn-primary' %>
 <% end %>
</div>

app/views/plants/show.html.erb
<h1>Welcome to the show page</h1>